// <auto-generated />
using ConsoleRpgEntities.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleRpgEntities.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20260514050029_C0049_SeedAbilitiesAndMagic")]
    partial class C0049_SeedAbilitiesAndMagic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AbilityCharacter", b =>
                {
                    b.Property<int>("AbilitiesId")
                        .HasColumnType("int");

                    b.Property<int>("CharactersId")
                        .HasColumnType("int");

                    b.HasKey("AbilitiesId", "CharactersId");

                    b.HasIndex("CharactersId");

                    b.ToTable("CharacterAbilities", (string)null);
                });

            modelBuilder.Entity("CharacterMagic", b =>
                {
                    b.Property<int>("CharactersId")
                        .HasColumnType("int");

                    b.Property<int>("MagicsId")
                        .HasColumnType("int");

                    b.HasKey("CharactersId", "MagicsId");

                    b.HasIndex("MagicsId");

                    b.ToTable("CharacterMagic", (string)null);
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Abilities.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryStat")
                        .HasColumnType("int");

                    b.Property<int>("StaminaCost")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CharacterType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RaceId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.HasIndex("RoomId");

                    b.ToTable("Characters");

                    b.HasDiscriminator<string>("CharacterType").HasValue("Character");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Containers.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContainerType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Containers");

                    b.HasDiscriminator<string>("ContainerType").HasValue("Container");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Door", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDiscovered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPickable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredKeyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomAId")
                        .HasColumnType("int");

                    b.Property<int>("RoomBId")
                        .HasColumnType("int");

                    b.Property<int>("TrapDamage")
                        .HasColumnType("int");

                    b.Property<bool>("TrapDisarmed")
                        .HasColumnType("bit");

                    b.Property<int>("TrapTypes")
                        .HasColumnType("int");

                    b.Property<int>("UnlockDC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomAId");

                    b.HasIndex("RoomBId");

                    b.ToTable("Doors");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.EquipmentSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int?>("EquipmentContainerId")
                        .HasColumnType("int");

                    b.Property<int?>("EquippedItemId")
                        .HasColumnType("int");

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("EquipmentContainerId");

                    b.HasIndex("EquippedItemId");

                    b.ToTable("EquipmentSlots");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContainerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("KeyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("ItemType").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Magic.Magic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BitPoolCost")
                        .HasColumnType("int");

                    b.Property<int>("BytePoolCost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Element")
                        .HasColumnType("int");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryStat")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Magics");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Races.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RaceType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Races");

                    b.HasDiscriminator<string>("RaceType").HasValue("Race");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Resources", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BitPool")
                        .HasColumnType("int");

                    b.Property<int>("BytePool")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("Hp")
                        .HasColumnType("int");

                    b.Property<int>("MaxBitPool")
                        .HasColumnType("int");

                    b.Property<int>("MaxBytePool")
                        .HasColumnType("int");

                    b.Property<int>("MaxHp")
                        .HasColumnType("int");

                    b.Property<int>("MaxSp")
                        .HasColumnType("int");

                    b.Property<int>("Sp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Skills.CharacterSkill", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("Proficiency")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("CharacterSkills");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Skills.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrimaryAttribute")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryAttribute")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Stats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("Constitution")
                        .HasColumnType("int");

                    b.Property<int>("Intellect")
                        .HasColumnType("int");

                    b.Property<int>("Intuition")
                        .HasColumnType("int");

                    b.Property<int>("Linguistic")
                        .HasColumnType("int");

                    b.Property<int>("Luck")
                        .HasColumnType("int");

                    b.Property<int>("Physique")
                        .HasColumnType("int");

                    b.Property<int>("Reflexes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Animal", b =>
                {
                    b.HasBaseType("ConsoleRpgEntities.Models.Character");

                    b.HasDiscriminator().HasValue("Animal");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Npc", b =>
                {
                    b.HasBaseType("ConsoleRpgEntities.Models.Character");

                    b.HasDiscriminator().HasValue("NPC");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Player", b =>
                {
                    b.HasBaseType("ConsoleRpgEntities.Models.Character");

                    b.HasDiscriminator().HasValue("Player");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Containers.Bookshelf", b =>
                {
                    b.HasBaseType("ConsoleRpgEntities.Models.Containers.Container");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.HasIndex("RoomId");

                    b.ToTable("Containers", t =>
                        {
                            t.Property("Description")
                                .HasColumnName("Bookshelf_Description");

                            t.Property("RoomId")
                                .HasColumnName("Bookshelf_RoomId");
                        });

                    b.HasDiscriminator().HasValue("Bookshelf");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Containers.Chest", b =>
                {
                    b.HasBaseType("ConsoleRpgEntities.Models.Containers.Container");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPickable")
                        .HasColumnType("bit");

                    b.Property<string>("RequiredKeyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("TrapDamage")
                        .HasColumnType("int");

                    b.Property<bool>("TrapDisarmed")
                        .HasColumnType("bit");

                    b.Property<int>("TrapTypes")
                        .HasColumnType("int");

                    b.Property<int>("UnlockDC")
                        .HasColumnType("int");

                    b.HasIndex("RoomId");

                    b.HasDiscriminator().HasValue("Chest");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Containers.Equipment", b =>
                {
                    b.HasBaseType("ConsoleRpgEntities.Models.Containers.Container");

                    b.Property<int?>("OwnerCharacterId")
                        .HasColumnType("int");

                    b.HasIndex("OwnerCharacterId")
                        .IsUnique()
                        .HasFilter("[OwnerCharacterId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Equipment");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Containers.Inventory", b =>
                {
                    b.HasBaseType("ConsoleRpgEntities.Models.Containers.Container");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("int");

                    b.Property<int?>("OwnerCharacterId")
                        .HasColumnType("int");

                    b.HasIndex("OwnerCharacterId")
                        .IsUnique()
                        .HasFilter("[OwnerCharacterId] IS NOT NULL");

                    b.ToTable("Containers", t =>
                        {
                            t.Property("OwnerCharacterId")
                                .HasColumnName("Inventory_OwnerCharacterId");
                        });

                    b.HasDiscriminator().HasValue("Inventory");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Containers.Room", b =>
                {
                    b.HasBaseType("ConsoleRpgEntities.Models.Containers.Container");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GridX")
                        .HasColumnType("int");

                    b.Property<int?>("GridY")
                        .HasColumnType("int");

                    b.ToTable("Containers", t =>
                        {
                            t.Property("Description")
                                .HasColumnName("Room_Description");
                        });

                    b.HasDiscriminator().HasValue("Room");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Items.Armor", b =>
                {
                    b.HasBaseType("ConsoleRpgEntities.Models.Items.Item");

                    b.Property<int>("DefenseRating")
                        .HasColumnType("int");

                    b.Property<int>("Durability")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int");

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.Property<int>("WeightClass")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Armor");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Items.Consumable", b =>
                {
                    b.HasBaseType("ConsoleRpgEntities.Models.Items.Item");

                    b.Property<int>("Effect")
                        .HasColumnType("int");

                    b.Property<int>("Potency")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Consumable");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Items.LockedJournal", b =>
                {
                    b.HasBaseType("ConsoleRpgEntities.Models.Items.Item");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPickable")
                        .HasColumnType("bit");

                    b.Property<string>("RequiredKeyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrapDamage")
                        .HasColumnType("int");

                    b.Property<bool>("TrapDisarmed")
                        .HasColumnType("bit");

                    b.Property<int>("TrapTypes")
                        .HasColumnType("int");

                    b.Property<int>("UnlockDC")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("LockedJournal");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Items.Tome", b =>
                {
                    b.HasBaseType("ConsoleRpgEntities.Models.Items.Item");

                    b.Property<string>("LoreText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Tome");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Items.Weapon", b =>
                {
                    b.HasBaseType("ConsoleRpgEntities.Models.Items.Item");

                    b.Property<int>("AttackPower")
                        .HasColumnType("int");

                    b.Property<int>("Durability")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int");

                    b.Property<int>("WeaponType")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Weapon");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Races.AnimalRace", b =>
                {
                    b.HasBaseType("ConsoleRpgEntities.Models.Races.Race");

                    b.HasDiscriminator().HasValue("Animal");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Races.MonsterRace", b =>
                {
                    b.HasBaseType("ConsoleRpgEntities.Models.Races.Race");

                    b.HasDiscriminator().HasValue("Monster");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Races.PlayableRace", b =>
                {
                    b.HasBaseType("ConsoleRpgEntities.Models.Races.Race");

                    b.HasDiscriminator().HasValue("Playable");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Wolf", b =>
                {
                    b.HasBaseType("ConsoleRpgEntities.Models.Npc");

                    b.Property<int>("PackSize")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Wolf");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Items.Shield", b =>
                {
                    b.HasBaseType("ConsoleRpgEntities.Models.Items.Armor");

                    b.HasDiscriminator().HasValue("Shield");
                });

            modelBuilder.Entity("AbilityCharacter", b =>
                {
                    b.HasOne("ConsoleRpgEntities.Models.Abilities.Ability", null)
                        .WithMany()
                        .HasForeignKey("AbilitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleRpgEntities.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterMagic", b =>
                {
                    b.HasOne("ConsoleRpgEntities.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleRpgEntities.Models.Magic.Magic", null)
                        .WithMany()
                        .HasForeignKey("MagicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Character", b =>
                {
                    b.HasOne("ConsoleRpgEntities.Models.Races.Race", "Race")
                        .WithMany("Characters")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConsoleRpgEntities.Models.Containers.Room", "Room")
                        .WithMany("Characters")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Race");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Door", b =>
                {
                    b.HasOne("ConsoleRpgEntities.Models.Containers.Room", "RoomA")
                        .WithMany("DoorsAsA")
                        .HasForeignKey("RoomAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConsoleRpgEntities.Models.Containers.Room", "RoomB")
                        .WithMany("DoorsAsB")
                        .HasForeignKey("RoomBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoomA");

                    b.Navigation("RoomB");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.EquipmentSlot", b =>
                {
                    b.HasOne("ConsoleRpgEntities.Models.Character", "Character")
                        .WithMany("EquipmentSlots")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleRpgEntities.Models.Containers.Equipment", "EquipmentContainer")
                        .WithMany("Slots")
                        .HasForeignKey("EquipmentContainerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConsoleRpgEntities.Models.Items.Item", "EquippedItem")
                        .WithMany()
                        .HasForeignKey("EquippedItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Character");

                    b.Navigation("EquipmentContainer");

                    b.Navigation("EquippedItem");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Items.Item", b =>
                {
                    b.HasOne("ConsoleRpgEntities.Models.Containers.Container", "Container")
                        .WithMany("ItemsCollection")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Container");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Resources", b =>
                {
                    b.HasOne("ConsoleRpgEntities.Models.Character", "Character")
                        .WithOne("Resources")
                        .HasForeignKey("ConsoleRpgEntities.Models.Resources", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Skills.CharacterSkill", b =>
                {
                    b.HasOne("ConsoleRpgEntities.Models.Character", "Character")
                        .WithMany("CharacterSkills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleRpgEntities.Models.Skills.Skill", "Skill")
                        .WithMany("CharacterSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Stats", b =>
                {
                    b.HasOne("ConsoleRpgEntities.Models.Character", "Character")
                        .WithOne("Stats")
                        .HasForeignKey("ConsoleRpgEntities.Models.Stats", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Containers.Bookshelf", b =>
                {
                    b.HasOne("ConsoleRpgEntities.Models.Containers.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Containers.Chest", b =>
                {
                    b.HasOne("ConsoleRpgEntities.Models.Containers.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Containers.Equipment", b =>
                {
                    b.HasOne("ConsoleRpgEntities.Models.Character", "Owner")
                        .WithOne("Equipment")
                        .HasForeignKey("ConsoleRpgEntities.Models.Containers.Equipment", "OwnerCharacterId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Containers.Inventory", b =>
                {
                    b.HasOne("ConsoleRpgEntities.Models.Character", "Owner")
                        .WithOne("Inventory")
                        .HasForeignKey("ConsoleRpgEntities.Models.Containers.Inventory", "OwnerCharacterId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Character", b =>
                {
                    b.Navigation("CharacterSkills");

                    b.Navigation("Equipment");

                    b.Navigation("EquipmentSlots");

                    b.Navigation("Inventory");

                    b.Navigation("Resources");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Containers.Container", b =>
                {
                    b.Navigation("ItemsCollection");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Races.Race", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Skills.Skill", b =>
                {
                    b.Navigation("CharacterSkills");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Containers.Equipment", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("ConsoleRpgEntities.Models.Containers.Room", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("DoorsAsA");

                    b.Navigation("DoorsAsB");
                });
#pragma warning restore 612, 618
        }
    }
}
